/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgriculturalExportRouteImport } from './routes/agricultural-export'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInsightsIndexRouteImport } from './routes/admin/insights/index'
import { Route as AdminInsightsNewRouteImport } from './routes/admin/insights/new'
import { Route as AdminInsightsIdEditRouteImport } from './routes/admin/insights/$id/edit'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalExportRoute = AgriculturalExportRouteImport.update({
  id: '/agricultural-export',
  path: '/agricultural-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsIndexRoute = AdminInsightsIndexRouteImport.update({
  id: '/admin/insights/',
  path: '/admin/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsNewRoute = AdminInsightsNewRouteImport.update({
  id: '/admin/insights/new',
  path: '/admin/insights/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsIdEditRoute = AdminInsightsIdEditRouteImport.update({
  id: '/admin/insights/$id/edit',
  path: '/admin/insights/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights': typeof AdminInsightsIndexRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agricultural-export'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/admin/login'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/insights/new'
    | '/admin/insights/'
    | '/admin/insights/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agricultural-export'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/admin/login'
    | '/insights/$slug'
    | '/admin'
    | '/insights'
    | '/admin/insights/new'
    | '/admin/insights'
    | '/admin/insights/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agricultural-export'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms'
    | '/why-choose-us'
    | '/admin/login'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/insights/new'
    | '/admin/insights/'
    | '/admin/insights/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgriculturalExportRoute: typeof AgriculturalExportRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  AdminInsightsNewRoute: typeof AdminInsightsNewRoute
  AdminInsightsIndexRoute: typeof AdminInsightsIndexRoute
  AdminInsightsIdEditRoute: typeof AdminInsightsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural-export': {
      id: '/agricultural-export'
      path: '/agricultural-export'
      fullPath: '/agricultural-export'
      preLoaderRoute: typeof AgriculturalExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights/': {
      id: '/admin/insights/'
      path: '/admin/insights'
      fullPath: '/admin/insights/'
      preLoaderRoute: typeof AdminInsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights/new': {
      id: '/admin/insights/new'
      path: '/admin/insights/new'
      fullPath: '/admin/insights/new'
      preLoaderRoute: typeof AdminInsightsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights/$id/edit': {
      id: '/admin/insights/$id/edit'
      path: '/admin/insights/$id/edit'
      fullPath: '/admin/insights/$id/edit'
      preLoaderRoute: typeof AdminInsightsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgriculturalExportRoute: AgriculturalExportRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  AdminLoginRoute: AdminLoginRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  AdminInsightsNewRoute: AdminInsightsNewRoute,
  AdminInsightsIndexRoute: AdminInsightsIndexRoute,
  AdminInsightsIdEditRoute: AdminInsightsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
