/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestAQuoteRouteImport } from './routes/request-a-quote'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NigerianCommoditySourcingRouteImport } from './routes/nigerian-commodity-sourcing'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GlobalSourcingRouteImport } from './routes/global-sourcing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgriculturalExportRouteImport } from './routes/agricultural-export'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as PlatformSignUpRouteImport } from './routes/platform/sign-up'
import { Route as PlatformSignInRouteImport } from './routes/platform/sign-in'
import { Route as PlatformForgotPasswordRouteImport } from './routes/platform/forgot-password'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated/admin.insights'
import { Route as AuthenticatedAdminInsightsNewRouteImport } from './routes/_authenticated/admin.insights.new'
import { Route as ApiPublicInsightsMediaSplatRouteImport } from './routes/api/public/insights/media.$'
import { Route as AuthenticatedAdminInsightsIdEditRouteImport } from './routes/_authenticated/admin.insights.$id.edit'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAQuoteRoute = RequestAQuoteRouteImport.update({
  id: '/request-a-quote',
  path: '/request-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NigerianCommoditySourcingRoute =
  NigerianCommoditySourcingRouteImport.update({
    id: '/nigerian-commodity-sourcing',
    path: '/nigerian-commodity-sourcing',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalSourcingRoute = GlobalSourcingRouteImport.update({
  id: '/global-sourcing',
  path: '/global-sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalExportRoute = AgriculturalExportRouteImport.update({
  id: '/agricultural-export',
  path: '/agricultural-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const PlatformSignUpRoute = PlatformSignUpRouteImport.update({
  id: '/platform/sign-up',
  path: '/platform/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSignInRoute = PlatformSignInRouteImport.update({
  id: '/platform/sign-in',
  path: '/platform/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformForgotPasswordRoute = PlatformForgotPasswordRouteImport.update({
  id: '/platform/forgot-password',
  path: '/platform/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/admin/insights',
    path: '/admin/insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInsightsNewRoute =
  AuthenticatedAdminInsightsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminInsightsRoute,
  } as any)
const ApiPublicInsightsMediaSplatRoute =
  ApiPublicInsightsMediaSplatRouteImport.update({
    id: '/api/public/insights/media/$',
    path: '/api/public/insights/media/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminInsightsIdEditRoute =
  AuthenticatedAdminInsightsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminInsightsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-sourcing': typeof GlobalSourcingRoute
  '/insights': typeof InsightsRouteWithChildren
  '/nigerian-commodity-sourcing': typeof NigerianCommoditySourcingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/platform/forgot-password': typeof PlatformForgotPasswordRoute
  '/platform/sign-in': typeof PlatformSignInRoute
  '/platform/sign-up': typeof PlatformSignUpRoute
  '/insights/': typeof InsightsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRouteWithChildren
  '/admin/insights/new': typeof AuthenticatedAdminInsightsNewRoute
  '/admin/insights/$id/edit': typeof AuthenticatedAdminInsightsIdEditRoute
  '/api/public/insights/media/$': typeof ApiPublicInsightsMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-sourcing': typeof GlobalSourcingRoute
  '/nigerian-commodity-sourcing': typeof NigerianCommoditySourcingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/platform/forgot-password': typeof PlatformForgotPasswordRoute
  '/platform/sign-in': typeof PlatformSignInRoute
  '/platform/sign-up': typeof PlatformSignUpRoute
  '/insights': typeof InsightsIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRouteWithChildren
  '/admin/insights/new': typeof AuthenticatedAdminInsightsNewRoute
  '/admin/insights/$id/edit': typeof AuthenticatedAdminInsightsIdEditRoute
  '/api/public/insights/media/$': typeof ApiPublicInsightsMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agricultural-export': typeof AgriculturalExportRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-sourcing': typeof GlobalSourcingRoute
  '/insights': typeof InsightsRouteWithChildren
  '/nigerian-commodity-sourcing': typeof NigerianCommoditySourcingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/platform/forgot-password': typeof PlatformForgotPasswordRoute
  '/platform/sign-in': typeof PlatformSignInRoute
  '/platform/sign-up': typeof PlatformSignUpRoute
  '/insights/': typeof InsightsIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRouteWithChildren
  '/_authenticated/admin/insights/new': typeof AuthenticatedAdminInsightsNewRoute
  '/_authenticated/admin/insights/$id/edit': typeof AuthenticatedAdminInsightsIdEditRoute
  '/api/public/insights/media/$': typeof ApiPublicInsightsMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agricultural-export'
    | '/auth'
    | '/contact'
    | '/global-sourcing'
    | '/insights'
    | '/nigerian-commodity-sourcing'
    | '/privacy-policy'
    | '/quote'
    | '/request-a-quote'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/platform/forgot-password'
    | '/platform/sign-in'
    | '/platform/sign-up'
    | '/insights/'
    | '/platform/'
    | '/admin/insights'
    | '/admin/insights/new'
    | '/admin/insights/$id/edit'
    | '/api/public/insights/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agricultural-export'
    | '/auth'
    | '/contact'
    | '/global-sourcing'
    | '/nigerian-commodity-sourcing'
    | '/privacy-policy'
    | '/quote'
    | '/request-a-quote'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/platform/forgot-password'
    | '/platform/sign-in'
    | '/platform/sign-up'
    | '/insights'
    | '/platform'
    | '/admin/insights'
    | '/admin/insights/new'
    | '/admin/insights/$id/edit'
    | '/api/public/insights/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agricultural-export'
    | '/auth'
    | '/contact'
    | '/global-sourcing'
    | '/insights'
    | '/nigerian-commodity-sourcing'
    | '/privacy-policy'
    | '/quote'
    | '/request-a-quote'
    | '/reset-password'
    | '/services'
    | '/terms'
    | '/terms-and-conditions'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/platform/forgot-password'
    | '/platform/sign-in'
    | '/platform/sign-up'
    | '/insights/'
    | '/platform/'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/insights/new'
    | '/_authenticated/admin/insights/$id/edit'
    | '/api/public/insights/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgriculturalExportRoute: typeof AgriculturalExportRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GlobalSourcingRoute: typeof GlobalSourcingRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  NigerianCommoditySourcingRoute: typeof NigerianCommoditySourcingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRoute
  RequestAQuoteRoute: typeof RequestAQuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  PlatformForgotPasswordRoute: typeof PlatformForgotPasswordRoute
  PlatformSignInRoute: typeof PlatformSignInRoute
  PlatformSignUpRoute: typeof PlatformSignUpRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  ApiPublicInsightsMediaSplatRoute: typeof ApiPublicInsightsMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-quote': {
      id: '/request-a-quote'
      path: '/request-a-quote'
      fullPath: '/request-a-quote'
      preLoaderRoute: typeof RequestAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nigerian-commodity-sourcing': {
      id: '/nigerian-commodity-sourcing'
      path: '/nigerian-commodity-sourcing'
      fullPath: '/nigerian-commodity-sourcing'
      preLoaderRoute: typeof NigerianCommoditySourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-sourcing': {
      id: '/global-sourcing'
      path: '/global-sourcing'
      fullPath: '/global-sourcing'
      preLoaderRoute: typeof GlobalSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural-export': {
      id: '/agricultural-export'
      path: '/agricultural-export'
      fullPath: '/agricultural-export'
      preLoaderRoute: typeof AgriculturalExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/platform/sign-up': {
      id: '/platform/sign-up'
      path: '/platform/sign-up'
      fullPath: '/platform/sign-up'
      preLoaderRoute: typeof PlatformSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/sign-in': {
      id: '/platform/sign-in'
      path: '/platform/sign-in'
      fullPath: '/platform/sign-in'
      preLoaderRoute: typeof PlatformSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/forgot-password': {
      id: '/platform/forgot-password'
      path: '/platform/forgot-password'
      fullPath: '/platform/forgot-password'
      preLoaderRoute: typeof PlatformForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/admin/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/insights/new': {
      id: '/_authenticated/admin/insights/new'
      path: '/new'
      fullPath: '/admin/insights/new'
      preLoaderRoute: typeof AuthenticatedAdminInsightsNewRouteImport
      parentRoute: typeof AuthenticatedAdminInsightsRoute
    }
    '/api/public/insights/media/$': {
      id: '/api/public/insights/media/$'
      path: '/api/public/insights/media/$'
      fullPath: '/api/public/insights/media/$'
      preLoaderRoute: typeof ApiPublicInsightsMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/insights/$id/edit': {
      id: '/_authenticated/admin/insights/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/insights/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminInsightsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminInsightsRoute
    }
  }
}

interface AuthenticatedAdminInsightsRouteChildren {
  AuthenticatedAdminInsightsNewRoute: typeof AuthenticatedAdminInsightsNewRoute
  AuthenticatedAdminInsightsIdEditRoute: typeof AuthenticatedAdminInsightsIdEditRoute
}

const AuthenticatedAdminInsightsRouteChildren: AuthenticatedAdminInsightsRouteChildren =
  {
    AuthenticatedAdminInsightsNewRoute: AuthenticatedAdminInsightsNewRoute,
    AuthenticatedAdminInsightsIdEditRoute:
      AuthenticatedAdminInsightsIdEditRoute,
  }

const AuthenticatedAdminInsightsRouteWithChildren =
  AuthenticatedAdminInsightsRoute._addFileChildren(
    AuthenticatedAdminInsightsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgriculturalExportRoute: AgriculturalExportRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GlobalSourcingRoute: GlobalSourcingRoute,
  InsightsRoute: InsightsRouteWithChildren,
  NigerianCommoditySourcingRoute: NigerianCommoditySourcingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRoute,
  RequestAQuoteRoute: RequestAQuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  PlatformForgotPasswordRoute: PlatformForgotPasswordRoute,
  PlatformSignInRoute: PlatformSignInRoute,
  PlatformSignUpRoute: PlatformSignUpRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  ApiPublicInsightsMediaSplatRoute: ApiPublicInsightsMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
